server:
  port: 8099
spring:
  application:
    name: cache-test
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cache_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&useLocalSessionState=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filters: stat,wall
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true

mybatis:
  type-aliases-package: jani.demo.cache.test.entity.**
  mapper-locations: classpath:mapper/*/*.xml

# jedis配置
jedis:
  host: 127.0.0.1
  port: 6379
  auth: foobared
  #  host: bj-crs-a5mm7jyi.sql.tencentcdb.com
  #  port: 24735
  #  auth: "xv35eH70!mms9vwa4uqd"
  maxActive: 1024
  maxIdle: 200
  maxWait: 10000
  timeOut: 10000
  testOnBorrow: true
  defaultDataBase: 9
  clientName: dlblog-jedis-client
  auto.destruction.ms: 10000
  lock.px: 3000
  lock.ex: 300
